default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: consistently_development
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: consistently_test
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: consistently_production
    username: consistently
    password: password
    host: localhost
    port: 5432

  cache:
    <<: *primary_production
    database: consistently_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: consistently_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: consistently_production_cable
    migrations_paths: db/cable_migrate
